name: Dependabot to Gerrit
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  open-or-update-change:
    runs-on: ubuntu-latest
    if: github.actor == 'addshore'
    steps:
      - name: Checkout HEAD commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Output infomation
        run: |
          echo ${GITHUB_REF}
          echo ${{ github.event.pull_request.base.ref }}
          cat .gitreview
          git log --format=%B -n1
          git diff --name-only HEAD~1 HEAD
          git diff HEAD~1 HEAD
      - name: Setup git config
        run: |
          git config user.name "Addbot[dependabot]"
          git config user.email "addshorewiki+addbot-dependabot@gmail.com"
      - name: Setup git remote
        run: |
          GITREVIEW_PROJECT=$(cat .gitreview | grep project= | sed "s/project=//" | sed "s/\.git//")
          GITREVIEW_HOST=$(cat .gitreview | grep host= | sed "s/host=//")
          # Create the authenticated remote for gerrit
          git remote add gerrit "https://addbot:${{ secrets.DEPENDABOT_GERRIT_PASSWORD }}@${GITREVIEW_HOST}/r/a/${GITREVIEW_PROJECT}"
      - name: Alter commit
        run: |
          # Add a Change-Id generated from the github branch
          # And claim the authorship of the commit
          OLD_MSG=$(git log --format=%B -n1)
          MSG_LINE=""
          # Generate the "randomness" for the change id from the branch name
          # This means that multiple alterations to the PR will submit to the same Gerrit change
          # This will result in the exact same update having the same Change-Id across multiple Gerrit repos
          random=$(echo ${GITHUB_REF} | git hash-object --stdin)
          git commit --reset-author --amend -m"$OLD_MSG" -m"Change-Id: I${random}"
          # And output the message
          git log --format=%B -n1
      - name: Submit to Gerrit
        run: |
          git push gerrit HEAD:refs/for/${{ github.event.pull_request.base.ref }}%ready;
