name: Build and test Wikibase and friends

on:
  workflow_dispatch:
    inputs:
      env_file_manual:
        description: 'Environment file'
        required: true
        default: '.env' # only gets set on a "workflow_dispatch" run
  push:

env:
  env_file_latest: 'versions/wmde5.env'
  env_file_previous: 'versions/wmde6.env'

jobs:

  provide_env_files:
      name: Collect env files
      runs-on: ubuntu-latest

      steps:
      - name: Collect env files
        run: |
          echo ${{ env.env_file_latest }}
          echo ${{ env.env_file_previous }}
          echo ${{ env.env_file_manual }}
      # this step is needed, so the output gets to the next defined job
      # outputs:
      #     matrix: ${{ steps.output_data.outputs.matrix }}

  # build_wikibase:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       env_file: ${{ env.env_files }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Do stuff
  #       run: echo ${{ env.env_file }}