name: TEST env vars

on:
  workflow_dispatch:
    inputs:
      multi_line:
        description: 'Environment file'
        required: true
        default: ''
jobs:

  stuff:
    runs-on: ubuntu-latest
    steps:
    - name: paste
      run: echo "${{ github.event.inputs.multi_line }}" > text
    - name: test
      run: cat text
