name: Fetch from Gerrit, Run stuff, Report back

on:
  workflow_dispatch:
    inputs:
      fetch-repo:
        description: 'repo to fetch'
        required: true
      fetch-ref:
        description: 'ref to fetch from repo'
        required: true
      run-scripts:
        description: 'files to run, JSON list. Example: `["echo foo","echo bar"]`'
        required: true
      report-change:
        description: 'change to report back to. Example: `456323,2`'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          run: ${{ fromJson(github.event.inputs.run-scripts)}}
    steps:
      - name: Fetch Code
        run: |
          git init . && git fetch "${{ github.event.inputs.fetch-repo }}" ${{ github.event.inputs.fetch-ref }} && git checkout FETCH_HEAD
      - name: Run Script
        run: |
          set -e
          ${{ matrix.run }}
      - name: Record failures
        if: ${{ !success() }}
        id: record
        run: echo "::set-output name=failure::true"


  report-back:
    if: always()
    needs: [ run ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gerrit SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ADDBOT_GERRIT_SSH }}
          known_hosts: ${{ secrets.GERRIT_KNOWN_HOST }}
      - name: Build Review JSON
        run: |
          set +e
          MSG_PRE=$([[ ${{needs.run.outputs.failure == true}} == true ]] && echo "Github Action Failed")
          MSG_PRE=$([[ ${{needs.run.outputs.failure == true}} == false ]] && echo "Github Action Success")
          RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_NUMBER}"
          REVIEW={}
          REVIEW=$(echo $REVIEW | jq --arg message "${MSG_PRE}: ${RUN_URL}" '. + {message: $message}')
          echo $REVIEW
      - name: Report to Gerrit
        run: |
          echo $REVIEW | ssh -p 29418 addbot@gerrit.wikimedia.org gerrit review --json ${{ github.event.inputs.report-change }}