name: Fetch from Gerrit and run File

on:
  workflow_dispatch:
    inputs:
      fetch-repo:
        description: 'repo to fetch'
        required: true
      fetch-ref:
        description: 'ref to fetch from repo'
        required: true
      run:
        description: 'file to run'
        required: true

jobs:
  run-file:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gerrit SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: gerrit.wikimedia.org
          private-key: ${{ secrets.ADDBOT_GERRIT_SSH }}
      - name: Fetch Code
        run: |
          git init . && git fetch "${{ github.event.inputs.fetch-repo }}" ${{ github.event.inputs.fetch-ref }} && git checkout FETCH_HEAD
      - name: Run Script
        run: |
          ${{ github.event.inputs.run }}
      # - name: report
      #   run: |
